INSERT INTO `challenge`.`pos`(`id`,`name`)VALUES(1,"CABA");
INSERT INTO `challenge`.`pos`(`id`,`name`)VALUES(2,"GBA_1");
INSERT INTO `challenge`.`pos`(`id`,`name`)VALUES(3,"GBA_2");
INSERT INTO `challenge`.`pos`(`id`,`name`)VALUES(4,"Santa Fe");
INSERT INTO `challenge`.`pos`(`id`,`name`)VALUES(5,"Córdoba");
INSERT INTO `challenge`.`pos`(`id`,`name`)VALUES(6,"Misiones");
INSERT INTO `challenge`.`pos`(`id`,`name`)VALUES(7,"Salta");
INSERT INTO `challenge`.`pos`(`id`,`name`)VALUES(8,"Chubut");
INSERT INTO `challenge`.`pos`(`id`,`name`)VALUES(9,"Santa Cruz");
INSERT INTO `challenge`.`pos`(`id`,`name`)VALUES(10,"Catamarca");